### ISSUE TITLE
Howe to save model?

### ISSUE THREAD

**Issue by prudhviraju535** [rojagtap/abstractive_summarizer#1]
Hi Rohan, 

Can you let me know when had how to save the model in h5 format. if i want to load from GPU to cpu?

**Comment by rojagtap** [comment]
> Hi Rohan,
> 
> Can you let me know when had how to save the model in h5 format. if i want to load from GPU to cpu?

A custom model cannot be saved using the SavedModel format (which is your model.save("model.h5"))
Not sure what you meant by GPU to CPU, but 

```
if ckpt_manager.latest_checkpoint:
    ckpt.restore(ckpt_manager.latest_checkpoint)
    print ('Latest checkpoint restored!!')
```

you can restore a model from a checkpoint file using the above lines of code. You can export the ckpt files and load the model from these.

Although, yes this method is not independent of source code and you have to have an architecture to restore the weights. 

You can tune in to my blog (section #8) to get a better understanding of the checkpoint saving and restoration:
https://towardsdatascience.com/10-tensorflow-tricks-every-ml-practitioner-must-know-96b860e53c1

Hope this will solve your issue:)

**Comment by prudhviraju535** [comment]
Hi Rohan,

I am planning to run my model and server(GPU) and once done i want to save the model and extract back to my laptop(cpu)  for prediction. regarding that i want to check with you  on how to save the model. so that i use for testing in different place or for deployment. is there a way to modify your code to run on multiple GPUs.

Thanks for the article..it nice

**Comment by rojagtap** [comment]
Hi! So here's a thing. TensorFlow has a distributed training API called tf.distributed. It offers multiple strategies that manage how the model is synced across various GPUs. Well, I don't have multiple GPUs so I cannot provide you with an exact working piece of code here, sorry :(. 

However, you can check the same article where I have given a general idea for distributed training using TensorFlow.

But in the end, refer the docs: https://www.tensorflow.org/tutorials/distribute/custom_training
