### ISSUE TITLE
help ,please

### ISSUE THREAD

**Issue by change0929** [rojagtap/abstractive_summarizer#10]
I have trained the model for 20 eopchs completly, but I couldn't get good result.Maybe 20 epochs result in underfitting or overfitting?PLEASE~

**Comment by rojagtap** [comment]
If you're not improving on your loss then probably it is underfitting, but it's difficult to tell for sure without any background. Can you maybe paste in a plot of losses or just the loss figures for your 20 epochs?

P.S. Is this the same data you're training on?

**Comment by akshitsehgal** [comment]
Hello. Thank you so much for this code it works amazingly. Though I was trying to export the model trained using this link: https://www.tensorflow.org/text/tutorials/transformer. But it's throwing me an error

![image](https://user-images.githubusercontent.com/84592564/194296496-2d326e58-af10-4150-89fa-3ae1d5109473.png)
![image](https://user-images.githubusercontent.com/84592564/194296644-30b0ce28-5272-4c74-8ec8-c9ae7b7d3e60.png)


It says AttributeError: 'Tensor' object has no attribute 'lower'

I need to export this model to use it in a flask app. Any help would be appreciated 
Thanks

**Comment by rojagtap** [comment]
As I can see from a high level, the issue starts when you use `ExportTranslator` for the function call, which is decorated using `@tf.function`. This constructs the graph for execution. I think if you remove `@tf.function`, i.e., make the execution eager, then this should work.

However, I understand that it can make your model slow and less deployable. The link you mentioned uses the `tf.data` API for preprocessing, see this:

```
def make_batches(ds):
  return (
      ds
      .shuffle(BUFFER_SIZE)
      .batch(BATCH_SIZE)
      .map(prepare_batch, tf.data.AUTOTUNE)
      .prefetch(buffer_size=tf.data.AUTOTUNE))

```
as opposed to my code:
```
dataset = tf.data.Dataset.from_tensor_slices((inputs, targets)).shuffle(BUFFER_SIZE).batch(BATCH_SIZE)
```

This API creates a seamless pipeline of data and enables end-to-end model execution from raw data to raw output. Unfortunately, I haven't used it in my code and have a static preprocessing which seems to be the root of your issue. If you can translate your data (at least the test or live data from your app) to the `tf.data` pipeline and pass that to the model, then you should be good, I guess.

LMK if that helps.

Thanks!

**Comment by akshitsehgal** [comment]
Hey there!
Sorry for the late reply but thankfully it worked
So thanks to you

I removed the decorator and it worked for now. Haven't tried creating tf.data api though.

However I want to save this model and use it somewhere else.
So when I save this model using `tf.saved_model.save(summarizer_model, 'save_dir')` , then load the model using
`model = tf.saved_model.load('save_dir')` and then try to run it it shows the following error:

![image](https://user-images.githubusercontent.com/84592564/199556336-92712f58-cb3a-4305-b813-28956f36bfca.png)

When I try saving it with `tf.keras.models.save_model(summarizer_model,'save_dir')`
I get the following error:
![image](https://user-images.githubusercontent.com/84592564/199556820-ec17eb73-8497-42c3-a345-52a3d2f7bfcb.png)

There is no problem running the model that was created with ExportTranslator above before saving it:
![image](https://user-images.githubusercontent.com/84592564/199557328-55ebbd1a-8cdc-47e0-9484-55cb603c089c.png)

Any help would be appreciated
Thanks in advance!

**Comment by rojagtap** [comment]
Unfortunately, i haven't come across this error. But I found this: https://github.com/tensorflow/tensorflow/issues/37439#issuecomment-600290097

I think you'll need to use `tf.keras.model.save`

Hope this helps

**Comment by akshitsehgal** [comment]
Thanks for the tip
I've tried this but doesn't work for me
I'll find a workaround and let you know

But yes thanks for the help!
Cheers!
