### ISSUE TITLE
GPU Utilisation Zero

### ISSUE THREAD

**Issue by subhamiitk** [rojagtap/abstractive_summarizer#11]
The training pipeline is not utilising the GPU. Can you please look into this? I tried doing this but still there was no success. 
```
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "0"

```

**Comment by subhamiitk** [comment]
OMG! It returns an empty list, but running `nvidia-smi` shows the available GPU. 
Tried `pip3 install --upgrade tensorflow-gpu ` and removed tensorflow and then installed `tensorflow-gpu ` ,but still the output is an empty list. 
![image](https://user-images.githubusercontent.com/19919668/131726910-8ab9f045-c7f5-470d-aa27-f84268160ca9.png)

**Comment by rojagtap** [comment]
`pip install tensorflow-gpu` is the old way and I think, is deprecated. I am assuming you have installed Cuda correctly as your `nvidia-smi` looks fine. Just try `pip (or pip3) install tensorflow`. And this time do a fresh start (maybe in a separate conda/venv). And let me know how it goes...
