### ISSUE TITLE
Can we save the model in PB format ?

### ISSUE THREAD

**Issue by prudhviraju535** [rojagtap/abstractive_summarizer#3]
Hi Rohan,

Is there a way to save the model using tf.save_model other then checkpoints in your summarization or can we convert existing checkpoints to PB format for deployment?

**Comment by rojagtap** [comment]
For deploying checkpoints: https://towardsdatascience.com/deploy-tensorflow-models-9813b5a705d5
For converting to pb: https://stackoverflow.com/questions/45864363/tensorflow-how-to-convert-meta-data-and-index-model-files-into-one-graph-pb

**Comment by prudhviraju535** [comment]
Hi Rohan, 
 i have trained it but the problem is .meta file for checkpoints are not getting created. Below are the only list of last checkpoint. is there a way for tensorflow(2.2)

Files list : 
1. checkpoint
2. ckpt-5.data-00000-of-00002
3. ckpt-5.data-00001-of-00002
4. ckpt-5.index

**Comment by rojagtap** [comment]
Try this: https://cloud.google.com/blog/products/ai-machine-learning/how-to-serve-deep-learning-models-using-tensorflow-2-0-with-cloud-functions
